[package]
name = "discord-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-rustls", "sqlite", "derive", "macros"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
